=== jirmed/PB138Task2/src/valid/company.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="company" type="companyType">
        <xs:key name="pid"> 
            <xs:selector xpath=".//person"/> 
            <xs:field xpath="@pid"/> 
        </xs:key> 
        <xs:key name="eid"> 
            <xs:selector xpath=".//employee"/> 
            <xs:field xpath="@eid"/> 
        </xs:key> 
        <xs:key name="did"> 
            <xs:selector xpath=".//division"/> 
            <xs:field xpath="@did"/> 
        </xs:key> 
    </xs:element>    
    <xs:complexType name="personType">
        <xs:sequence>
            <xs:element type="nonEmptyString" name="name" />
            <xs:element type="nonEmptyString" name="surname" />
            <xs:element type="amountType" name="salary" />
            <xs:element type="xs:string" name="note" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute type="xs:positiveInteger" name="pid" use="required"/>
    </xs:complexType>
    <xs:complexType name="headType">
        <xs:sequence>
            <xs:element type="personType" name="person" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="employeeType">
        <xs:sequence>
            <xs:element type="employeeNameType" name="name" minOccurs="0" />
            <xs:element type="amountType" name="salary" minOccurs="0" />
            <xs:element type="xs:string" name="company" minOccurs="0" />
            <xs:element type="amountType" name="fee" minOccurs="0" />
            <xs:element type="yesNo" name="vat" minOccurs="0" />
        </xs:sequence>
        <xs:attribute type="categoryType" name="category" use="required"/>
        <xs:attribute type="xs:positiveInteger" name="eid" use="required"/>
    </xs:complexType>
    <xs:complexType name="employeesType">
        <xs:sequence>
            <xs:element type="employeeType" name="employee" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="divisionType">
        <xs:sequence>
            <xs:element type="xs:string" name="name" minOccurs="0" />
            <xs:element type="headType" name="head" minOccurs="0"  />
            <xs:element type="employeesType" name="employees" minOccurs="0" />
        </xs:sequence>
        <xs:attribute type="nonEmptyString" name="did" use="required"/>
    </xs:complexType>
    <xs:complexType name="companyType">
        <xs:sequence>
            <xs:element type="divisionType" name="division" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="amountType">
        <xs:restriction base="xs:decimal">
            <xs:pattern value="\d+\.\d{2}" />
            <xs:minExclusive value="0" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="employeeNameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]*\s[A-Z][a-z]*" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="categoryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="worker" />
            <xs:enumeration value="contractor" />
            <xs:enumeration value="developer" />
            <xs:enumeration value="thp" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="yesNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes" />
            <xs:enumeration value="no" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== jirmed/PB138Task2/src/valid/notetestcompany.xml
<?xml version="1.0" encoding="utf-8"?>

<company
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="company.xsd">

    
    <!-- did is required, a nonempty string unique for all divisions,
      (can be used as a key for divisions)
      mandatory element - there must be always at least one division in the company
    -->
    <division did="production_zlin">
        <!-- name is optional and contains a string -->
        <name>Production factory Zlín</name>
        <!-- head is optional and contains always a person if present -->
        <head>
            <!-- mandatory element person, pid is required, unique (positive) integer 
            (can be used as a key for persons);
            the name, surname, salary elts. can be ordered in any order
            -->
            <person pid="1"> 	
                <!-- name is required, non-empty string -->	 
                <name>Pavel</name>	 
                <!-- surname is required, non-empty string -->
                <surname>Novák</surname> 
                <!-- salary is required, positive number 
	             with 2 decimal places precision, e.g. 10000.50 -->
                <salary>20000.00</salary> 
                <!-- note optional element, repeatable, contains any string -->  
                <note>Poznámka</note>   
            </person>            
        </head>
    </division>
    <division did="development_brno">
        <head>
            <person pid="2">
                <name>Jan</name>
                <surname>Novák</surname>
                <salary>200000.00</salary>
            </person>
        </head>
    </division>
    <division did="headquarter">
        <head>
            <person pid="3">
                <name>Jana</name>
                <surname>Nováková</surname>
                <salary>300000.00</salary>
                <note>Hlavní vedoucí</note>
                <note>Velmi šikovná</note>
                <note>administrativní pracovnice</note>
            </person>
      </head>
    </division>
</company>

=== jirmed/PB138Task2/src/valid/missingheadcompany.xml
<?xml version="1.0" encoding="utf-8"?>

<company
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="company.xsd">

    
    <!-- did is required, a nonempty string unique for all divisions,
      (can be used as a key for divisions)
      mandatory element - there must be always at least one division in the company
    -->
    <division did="production_zlin">
        <!-- name is optional and contains a string -->
        <name>Production factory Zlín</name>
        <!-- head is optional and contains always a person if present -->
        <employees><!-- optional element, products of the division. Must contain one or more 
                    elements product-->
            <employee category="worker" eid="1"> <!-- Mandatory element, Division Commodity. attribute
                                      category is required, contains non-empty letter string without 
                                      whitespace(s)-->
                <name>Sipecka Rychle</name>
                <salary>15000.00</salary>
            </employee>
           
        </employees>
    </division>
    <division did="development_brno">
        <head>
            <person pid="2">
                <name>Jan</name>
                <surname>Novák</surname>
                <salary>200000.00</salary>
            </person>
        </head>
        
    </division>
</company>

=== jirmed/PB138Task2/src/valid/noemployeescompany.xml
<?xml version="1.0" encoding="utf-8"?>

<company
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="company.xsd">

    
    <!-- did is required, a nonempty string unique for all divisions,
      (can be used as a key for divisions)
      mandatory element - there must be always at least one division in the company
    -->
    <division did="production_zlin">
        <!-- name is optional and contains a string -->
        <name>Production factory Zlín</name>
        <!-- head is optional and contains always a person if present -->
        <head>
            <!-- mandatory element person, pid is required, unique (positive) integer 
            (can be used as a key for persons);
            the name, surname, salary elts. can be ordered in any order
            -->
            <person pid="1"> 	
                <!-- name is required, non-empty string -->	 
                <name>Pavel</name>	 
                <!-- surname is required, non-empty string -->
                <surname>Novák</surname> 
                <!-- salary is required, positive number 
	             with 2 decimal places precision, e.g. 10000.50 -->
                <salary>20000.00</salary> 
                <!-- note optional element, repeatable, contains any string -->  
                <note>Poznámka</note>   
            </person>            
        </head>
    </division>
 </company>
